# Site settings
title: littlemountainman blog
email:
description: "living in the cloud - moving to vr soon"

url: "http://littlemountainman.github.io/blog"
twitter_username: littlemtman
github_username:  littlemountainman
baseurl: "/blog"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
